<?php
return [
    'ssl_tf'                => (env('APP_ENV') == 'dev' ? null : true),
    'domain_alias'          => 'app.',
    'site_domain'           => (env('APP_ENV') == 'dev' ? 'app.conversionperfectdev.test' : 'conversionperfect.com'),
    'site_domain_name'      => (env('APP_ENV') == 'dev' ? 'app.conversionperfectdev' : 'conversionperfect'),
    'admin_email'           => 'admin@conversionperfect.com',
    'avatar_path'           => 'avatars/',
    'support_email'         => 'support@conversionperfect.com',
    'support_url'           => 'https://support.conversionperfect.com',
    'full_url'              => 'conversionperfect.com',
    'api_token'             => 'g97Bw8QdwqARtzZ9aXUKqje9',
    'billing_flag'          => 0,
    'link_check_min'        => 10,
    'db_prefix'             => '',
    'home_url'              => (env('APP_ENV') == 'dev' ? 'http://app.conversionperfectdev.test' : 'https://conversionperfect.com'),
    'sys_temp_creators'     => ((env('SYSTEM_TEMPLATE_CREATORS') && env('SYSTEM_TEMPLATE_CREATORS') != '') ?
        env('SYSTEM_TEMPLATE_CREATORS') : "rmadison@lightspeedtech.com,daddy@themadisons.ca"),
    'standard_plan_id'      => ['14'],
    'social_plan_id'        => ['14', '15'],
    'aweber_consumerKey'    => env('AWEBER_CONSUMERKEY', 'AkkCWion3lehCDE2WG28BGp4'),
    'aweber_consumerSecret' => env('AWEBER_CONSUMERSECRET', 'Iop7B89l17MFZOnFGpWVl4yELKPJFXqJiWyRLzmH'),
    'cs_ct_api_key'         => env('CONSTANT_CONTACT_API_KEY', '6a850c69-645d-45d1-b230-90849bf4d345'),
    'cs_ct_secret'          => env('CONSTANT_CONTACT_SECRET', 'Ry3klANGjyS_oXXQxl7ZlA'),
];
